# PostgreSQL
#   Ensure the PostgreSQL gem is defined in your Gemfile
#   gem 'pg'
development:
  adapter: postgresql
  encoding: utf8
  database: railsbricks_1306_development
  username: timothychepeleff
  host: localhost
  pool: 5
  port: 5432
  
